CREATE TABLE IF NOT EXISTS contact (
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) DEFAULT NULL,
  title VARCHAR(10) DEFAULT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);